
export const metadata = {
  title: 'Create Zmes Project App',
  description: 'Generated by create zmes project page',
}

export default function Layout({ children }) {
  return (
    <>{children}</>
  )
}