// // https://www.youtube.com/watch?v=KvoFvmu5eRo
import Header from '@/components/header'
import Footer from '@/components/footer'
import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Create Zmes App',
  description: 'Generated by create zmes app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <div>{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
